import { NegativePromptCategory } from '@shared/mockupTypes';

export const TECHNICAL_FLAWS: NegativePromptCategory = {
  id: 'technical-flaws',
  name: 'Technical Quality Flaws',
  description: 'Critical technical issues that destroy image quality and realism',
  severity: 'critical',
  applicableFor: ['all'],
  prompts: [
    'blurry',
    'out of focus',
    'soft focus',
    'motion blur',
    'bokeh on subject',
    'unfocused',
    'lack of sharpness',
    'fuzzy details',
    'grainy',
    'noisy',
    'pixelated',
    'jpeg artifacts',
    'compression artifacts',
    'digital noise',
    'ISO noise',
    'banding',
    'posterization',
    'color banding',
    'overexposed',
    'underexposed',
    'blown out highlights',
    'crushed blacks',
    'clipped highlights',
    'loss of detail in shadows',
    'extreme contrast',
    'washed out colors',
    'color cast',
    'wrong white balance',
    'oversaturated',
    'undersaturated',
    'unnatural colors',
    'incorrect skin tones',
    'color fringing',
    'chromatic aberration',
    'purple fringing',
    'lens distortion',
    'barrel distortion',
    'pincushion distortion',
    'perspective distortion',
    'warped lines',
    'curved straight lines',
    'fisheye effect',
    'stretched proportions'
  ]
};

export const AI_ARTIFACTS: NegativePromptCategory = {
  id: 'ai-artifacts',
  name: 'AI Generation Artifacts',
  description: 'Common problems specific to AI-generated images',
  severity: 'critical',
  applicableFor: ['all'],
  prompts: [
    'deformed',
    'disfigured',
    'malformed',
    'mutated',
    'ugly',
    'poorly drawn',
    'bad anatomy',
    'wrong anatomy',
    'extra limbs',
    'missing limbs',
    'floating limbs',
    'disconnected limbs',
    'mutation',
    'mutilated',
    'bad hands',
    'fused fingers',
    'too many fingers',
    'missing fingers',
    'extra fingers',
    'long neck',
    'duplicate',
    'morbid',
    'mutilated hands',
    'poorly drawn hands',
    'poorly drawn face',
    'bad proportions',
    'extra heads',
    'two heads',
    'two faces',
    'two of the same object',
    'cloned',
    'copy',
    'watermark',
    'signature',
    'text',
    'logo',
    'username',
    'copyright',
    'dated',
    'timestamp',
    'words',
    'letters',
    'writing',
    'signed',
    'low quality',
    'low res',
    'normal quality',
    'worst quality',
    'error',
    'cropped',
    'lowres',
    'draft',
    'sketch'
  ]
};

export const UNWANTED_STYLES: NegativePromptCategory = {
  id: 'unwanted-styles',
  name: 'Unwanted Style Elements',
  description: 'Style and aesthetic elements that conflict with photorealism',
  severity: 'high',
  applicableFor: ['photorealistic-mockups'],
  prompts: [
    'painting',
    'drawing',
    'illustration',
    'sketch',
    'cartoon',
    'anime',
    'comic',
    'graphic novel',
    '3D render',
    'CGI',
    'digital art',
    'concept art',
    'oil painting',
    'watercolor',
    'pencil drawing',
    'artistic',
    'stylized',
    'abstract',
    'surreal',
    'fantasy',
    'unrealistic',
    'imaginary',
    'fictional',
    'fake looking',
    'computer generated look',
    'synthetic',
    'HDR',
    'excessive HDR',
    'over-processed',
    'heavy filters',
    'Instagram filter',
    'fake colors',
    'artificial saturation',
    'over-sharpened',
    'halo effect',
    'excessive clarity',
    'vintage',
    'retro',
    'old photo',
    'aged',
    'antique',
    'sepia',
    'black and white',
    'grayscale',
    'monochrome',
    'faded',
    'screenshot',
    'phone camera',
    'amateur photo',
    'selfie',
    'webcam',
    'security camera',
    'CCTV',
    'dashcam',
    'screen capture'
  ]
};

export const APPAREL_NEGATIVES: NegativePromptCategory = {
  id: 'apparel-negatives',
  name: 'Apparel Specific Exclusions',
  description: 'Negative prompts specific to apparel and t-shirt mockups',
  severity: 'high',
  applicableFor: ['apparel', 't-shirt', 'clothing'],
  prompts: [
    'distorted print',
    'warped design',
    'stretched graphic',
    'compressed design',
    'skewed text',
    'unreadable text',
    'design not following fabric contours',
    'flat design on curved surface',
    'design floating above fabric',
    'design not wrapping correctly',
    'wrinkled',
    'creased',
    'folded incorrectly',
    'bunched up',
    'stretched fabric',
    'saggy',
    'ill-fitting',
    'too tight',
    'too loose',
    'poor draping',
    'stiff fabric',
    'unnatural fabric behavior',
    'pixelated print',
    'low resolution design',
    'blurry graphics',
    'faded print',
    'cracked print',
    'peeling design',
    'vintage distressed when shouldn\'t be',
    'wrong print technique look',
    'wrong size',
    'incorrect proportions',
    'uneven seams',
    'twisted garment',
    'inside out',
    'backwards',
    'incorrect neckline',
    'wrong collar',
    'misshapen',
    'awkward pose',
    'stiff posture',
    'unnatural expression',
    'forced smile',
    'uncomfortable looking',
    'bad body proportions',
    'unrealistic figure',
    'wrong fabric color',
    'color bleeding',
    'uneven color',
    'faded areas',
    'discolored',
    'wrong undertone',
    'wrong setting',
    'inappropriate background',
    'distracting elements',
    'cluttered background',
    'competing focal points'
  ]
};

export const HUMAN_SUBJECT_NEGATIVES: NegativePromptCategory = {
  id: 'human-subject-negatives',
  name: 'Human Subject Quality Control',
  description: 'Negative prompts for images featuring people/models',
  severity: 'critical',
  applicableFor: ['lifestyle', 'model-photography', 'portrait'],
  prompts: [
    'bad face',
    'ugly face',
    'deformed face',
    'asymmetrical face',
    'cross-eyed',
    'wrong eyes',
    'dead eyes',
    'blank expression',
    'weird expression',
    'creepy',
    'unsettling',
    'bad anatomy',
    'wrong proportions',
    'extra limbs',
    'missing limbs',
    'extra arms',
    'extra legs',
    'fused limbs',
    'broken limbs',
    'twisted limbs',
    'floating limbs',
    'disconnected body parts',
    'bad hands',
    'deformed hands',
    'fused fingers',
    'extra fingers',
    'missing fingers',
    'six fingers',
    'too many fingers',
    'long fingers',
    'broken fingers',
    'mutated hands',
    'poorly drawn hands',
    'plastic skin',
    'waxy skin',
    'unnatural skin texture',
    'overly smooth skin',
    'fake skin',
    'doll-like',
    'mannequin',
    'awkward pose',
    'unnatural pose',
    'uncomfortable position',
    'stiff',
    'rigid',
    'forced',
    'mannequin pose',
    'multiple people when should be one',
    'crowd when should be single subject',
    'partial person',
    'cut off person',
    'headless',
    'floating head'
  ]
};

export function getNegativePrompts(productType?: string, includesHuman?: boolean): string {
  let negatives: string[] = [];

  negatives.push(...TECHNICAL_FLAWS.prompts);
  negatives.push(...AI_ARTIFACTS.prompts);
  negatives.push(...UNWANTED_STYLES.prompts);

  if (productType === 'apparel' || productType === 't-shirt' || productType === 'clothing' || productType === 'dtg-apparel' || productType === 'aop-apparel') {
    negatives.push(...APPAREL_NEGATIVES.prompts);
  }

  if (includesHuman) {
    negatives.push(...HUMAN_SUBJECT_NEGATIVES.prompts);
  }

  const uniqueNegatives = Array.from(new Set(negatives));
  return uniqueNegatives.join(', ');
}
