/**
 * TEEN PERSONAS (Ages 13-17)
 * Complete collection of 112 teen personas
 * 56 Female + 56 Male
 * 8 ethnicities × 7 sizes each
 * 
 * Version: 1.0
 * Date: December 4, 2024
 */

import { Sex, Ethnicity, UnifiedPersona } from '../../types';

type TeenPersonaData = Partial<Record<Sex, Partial<Record<Ethnicity, Partial<Record<string, UnifiedPersona[]>>>>>>;

export const TEEN_PERSONAS: TeenPersonaData = {
  'Female': {
    'White': {
      'XS': [{
        id: 'WHT_TN_F_XS_001',
        name: 'Lily',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'White',
        size: 'XS',
        height: '152cm (5\'0")',
        weight: '42kg (93lbs)',
        build: 'Petite developing frame with subtle curves',
        facialFeatures: 'Youthful oval face with soft features, smooth clear skin, bright blue eyes, teenage freshness',
        hairStyle: 'Long wavy',
        hairColor: 'Light brown',
        eyeColor: 'Blue',
        skinTone: 'Fair',
        fullDescription: 'Lily is a petite 15-year-old White girl with a developing frame. Her youthful oval face has soft features with smooth clear skin and bright blue eyes. She has long wavy light brown hair and maintains a petite build at 152cm with subtle emerging curves.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'WHT_TN_F_S_001',
        name: 'Emma',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'White',
        size: 'S',
        height: '158cm (5\'2")',
        weight: '48kg (106lbs)',
        build: 'Slim developing athletic build',
        facialFeatures: 'Heart-shaped youthful face, clear complexion, bright green eyes, teenage energy',
        hairStyle: 'Medium straight with bangs',
        hairColor: 'Blonde',
        eyeColor: 'Green',
        skinTone: 'Light',
        fullDescription: 'Emma is a 16-year-old White girl with a slim developing athletic build. Her heart-shaped youthful face has a clear complexion and bright green eyes. She has medium straight blonde hair with bangs and maintains a slim build at 158cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'WHT_TN_F_M_001',
        name: 'Olivia',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'White',
        size: 'M',
        height: '160cm (5\'3")',
        weight: '54kg (119lbs)',
        build: 'Average developing build with natural curves',
        facialFeatures: 'Oval face with teenage features, smooth skin, hazel eyes, youthful expression',
        hairStyle: 'Long layered',
        hairColor: 'Dark blonde',
        eyeColor: 'Hazel',
        skinTone: 'Medium fair',
        fullDescription: 'Olivia is a 16-year-old White girl with an average developing build. Her oval face has teenage features with smooth skin and hazel eyes. She has long layered dark blonde hair and a balanced build at 160cm with natural developing curves.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'WHT_TN_F_L_001',
        name: 'Sophia',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'White',
        size: 'L',
        height: '162cm (5\'4")',
        weight: '64kg (141lbs)',
        build: 'Curvy developing build with fuller figure',
        facialFeatures: 'Round youthful face, full cheeks, clear skin, blue eyes, teenage softness',
        hairStyle: 'Medium curly',
        hairColor: 'Auburn',
        eyeColor: 'Blue',
        skinTone: 'Fair with freckles',
        fullDescription: 'Sophia is a 17-year-old White girl with a curvy developing build. Her round youthful face has full cheeks with clear skin and blue eyes. She has medium curly auburn hair and maintains a fuller figure at 162cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'WHT_TN_F_XL_001',
        name: 'Ava',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'White',
        size: 'XL',
        height: '160cm (5\'3")',
        weight: '74kg (163lbs)',
        build: 'Plus-size developing build with full curves',
        facialFeatures: 'Full round youthful face, fuller cheeks, clear skin, gray-blue eyes, teenage features',
        hairStyle: 'Shoulder-length straight',
        hairColor: 'Light brown',
        eyeColor: 'Gray-blue',
        skinTone: 'Fair',
        fullDescription: 'Ava is a 16-year-old White girl with a plus-size developing build. Her full round youthful face has fuller cheeks with clear skin and gray-blue eyes. She has shoulder-length straight light brown hair and a fuller build at 160cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'WHT_TN_F_XXL_001',
        name: 'Mia',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'White',
        size: 'XXL',
        height: '163cm (5\'4")',
        weight: '86kg (190lbs)',
        build: 'Full-figured developing build',
        facialFeatures: 'Fuller round youthful face, soft features, clear teenage skin, hazel eyes',
        hairStyle: 'Long wavy',
        hairColor: 'Dark brown',
        eyeColor: 'Hazel',
        skinTone: 'Medium fair',
        fullDescription: 'Mia is a 17-year-old White girl with a full-figured developing build. Her fuller round youthful face has soft features with clear teenage skin and hazel eyes. She has long wavy dark brown hair and a full build at 163cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'WHT_TN_F_XXXL_001',
        name: 'Charlotte',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'White',
        size: 'XXXL',
        height: '165cm (5\'5")',
        weight: '98kg (216lbs)',
        build: 'Very full-figured developing build',
        facialFeatures: 'Very full round youthful face, fuller features, teenage skin, blue eyes',
        hairStyle: 'Medium straight',
        hairColor: 'Blonde',
        eyeColor: 'Blue',
        skinTone: 'Light',
        fullDescription: 'Charlotte is a 16-year-old White girl with a very full-figured developing build. Her very full round youthful face has fuller features with teenage skin and blue eyes. She has medium straight blonde hair and a very full build at 165cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Black': {
      'XS': [{
        id: 'BLK_TN_F_XS_001',
        name: 'Aaliyah',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Black',
        size: 'XS',
        height: '150cm (4\'11")',
        weight: '40kg (88lbs)',
        build: 'Petite slim developing frame',
        facialFeatures: 'Youthful oval face, smooth dark skin, high cheekbones, bright expressive eyes, teenage freshness',
        hairStyle: 'Natural curls',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Deep brown',
        fullDescription: 'Aaliyah is a petite 14-year-old Black girl with a slim developing frame. Her youthful oval face has smooth dark skin with high cheekbones and bright expressive eyes. She has natural black curls and maintains a petite build at 150cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'BLK_TN_F_S_001',
        name: 'Zoe',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Black',
        size: 'S',
        height: '157cm (5\'2")',
        weight: '47kg (104lbs)',
        build: 'Slim athletic developing build',
        facialFeatures: 'Heart-shaped youthful face, clear smooth complexion, defined features, teenage energy',
        hairStyle: 'Medium braids',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Rich brown',
        fullDescription: 'Zoe is a 16-year-old Black girl with a slim athletic developing build. Her heart-shaped youthful face has a clear smooth complexion with defined features. She has medium black braids and maintains a slim build at 157cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'BLK_TN_F_M_001',
        name: 'Imani',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Black',
        size: 'M',
        height: '160cm (5\'3")',
        weight: '55kg (121lbs)',
        build: 'Average developing build with natural curves',
        facialFeatures: 'Oval youthful face, smooth skin, full lips, expressive eyes, teenage features',
        hairStyle: 'Long straight (relaxed)',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Medium brown',
        fullDescription: 'Imani is a 16-year-old Black girl with an average developing build. Her oval youthful face has smooth skin with full lips and expressive eyes. She has long straight relaxed black hair and a balanced build at 160cm with natural developing curves.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'BLK_TN_F_L_001',
        name: 'Destiny',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Black',
        size: 'L',
        height: '163cm (5\'4")',
        weight: '66kg (145lbs)',
        build: 'Curvy developing build with fuller figure',
        facialFeatures: 'Round youthful face, fuller cheeks, smooth skin, dark eyes, teenage softness',
        hairStyle: 'Medium natural curly',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Dark brown',
        fullDescription: 'Destiny is a 17-year-old Black girl with a curvy developing build. Her round youthful face has fuller cheeks with smooth skin and dark eyes. She has medium natural curly black hair and maintains a fuller figure at 163cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'BLK_TN_F_XL_001',
        name: 'Jasmine',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Black',
        size: 'XL',
        height: '160cm (5\'3")',
        weight: '76kg (168lbs)',
        build: 'Plus-size developing build with full curves',
        facialFeatures: 'Full round youthful face, fuller features, clear skin, expressive eyes, teenage features',
        hairStyle: 'Short natural TWA',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Deep brown',
        fullDescription: 'Jasmine is a 16-year-old Black girl with a plus-size developing build. Her full round youthful face has fuller features with clear skin and expressive eyes. She has a short natural TWA (teeny weeny afro) and a fuller build at 160cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'BLK_TN_F_XXL_001',
        name: 'Maya',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Black',
        size: 'XXL',
        height: '165cm (5\'5")',
        weight: '88kg (194lbs)',
        build: 'Full-figured developing build',
        facialFeatures: 'Fuller round youthful face, soft features, smooth teenage skin, dark brown eyes',
        hairStyle: 'Medium locs',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Rich dark brown',
        fullDescription: 'Maya is a 17-year-old Black girl with a full-figured developing build. Her fuller round youthful face has soft features with smooth teenage skin and dark brown eyes. She has medium locs and a full build at 165cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'BLK_TN_F_XXXL_001',
        name: 'Diamond',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Black',
        size: 'XXXL',
        height: '163cm (5\'4")',
        weight: '100kg (220lbs)',
        build: 'Very full-figured developing build',
        facialFeatures: 'Very full round youthful face, fuller features, teenage skin, brown eyes',
        hairStyle: 'Short cropped',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Deep brown',
        fullDescription: 'Diamond is a 16-year-old Black girl with a very full-figured developing build. Her very full round youthful face has fuller features with teenage skin and brown eyes. She has short cropped black hair and a very full build at 163cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Hispanic': {
      'XS': [{
        id: 'HSP_TN_F_XS_001',
        name: 'Sofia',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Hispanic',
        size: 'XS',
        height: '152cm (5\'0")',
        weight: '41kg (90lbs)',
        build: 'Petite compact developing frame',
        facialFeatures: 'Youthful oval face, smooth olive skin, expressive dark eyes, teenage freshness',
        hairStyle: 'Long straight',
        hairColor: 'Dark brown',
        eyeColor: 'Dark brown',
        skinTone: 'Warm olive',
        fullDescription: 'Sofia is a petite 15-year-old Hispanic girl with a compact developing frame. Her youthful oval face has smooth olive skin with expressive dark eyes. She has long straight dark brown hair and maintains a petite build at 152cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'HSP_TN_F_S_001',
        name: 'Isabella',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Hispanic',
        size: 'S',
        height: '155cm (5\'1")',
        weight: '46kg (101lbs)',
        build: 'Slim athletic developing build',
        facialFeatures: 'Heart-shaped youthful face, clear complexion, bright brown eyes, teenage energy',
        hairStyle: 'Medium wavy',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Medium olive',
        fullDescription: 'Isabella is a 16-year-old Hispanic girl with a slim athletic developing build. Her heart-shaped youthful face has a clear complexion with bright brown eyes. She has medium wavy black hair and maintains a slim build at 155cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'HSP_TN_F_M_001',
        name: 'Camila',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Hispanic',
        size: 'M',
        height: '158cm (5\'2")',
        weight: '52kg (115lbs)',
        build: 'Average developing build with natural curves',
        facialFeatures: 'Oval youthful face, smooth tan skin, warm eyes, teenage features',
        hairStyle: 'Long layered',
        hairColor: 'Dark brown',
        eyeColor: 'Hazel-brown',
        skinTone: 'Warm tan',
        fullDescription: 'Camila is a 16-year-old Hispanic girl with an average developing build. Her oval youthful face has smooth tan skin with warm eyes. She has long layered dark brown hair and a balanced build at 158cm with natural developing curves.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'HSP_TN_F_L_001',
        name: 'Valentina',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Hispanic',
        size: 'L',
        height: '160cm (5\'3")',
        weight: '62kg (137lbs)',
        build: 'Curvy developing build with fuller figure',
        facialFeatures: 'Round youthful face, fuller cheeks, clear skin, dark eyes, teenage softness',
        hairStyle: 'Medium curly',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Golden olive',
        fullDescription: 'Valentina is a 17-year-old Hispanic girl with a curvy developing build. Her round youthful face has fuller cheeks with clear skin and dark eyes. She has medium curly black hair and maintains a fuller figure at 160cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'HSP_TN_F_XL_001',
        name: 'Gabriela',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Hispanic',
        size: 'XL',
        height: '158cm (5\'2")',
        weight: '72kg (159lbs)',
        build: 'Plus-size developing build with full curves',
        facialFeatures: 'Full round youthful face, fuller features, smooth skin, brown eyes, teenage features',
        hairStyle: 'Shoulder-length straight',
        hairColor: 'Dark brown',
        eyeColor: 'Brown',
        skinTone: 'Warm olive',
        fullDescription: 'Gabriela is a 16-year-old Hispanic girl with a plus-size developing build. Her full round youthful face has fuller features with smooth skin and brown eyes. She has shoulder-length straight dark brown hair and a fuller build at 158cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'HSP_TN_F_XXL_001',
        name: 'Mariana',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Hispanic',
        size: 'XXL',
        height: '162cm (5\'4")',
        weight: '84kg (185lbs)',
        build: 'Full-figured developing build',
        facialFeatures: 'Fuller round youthful face, soft features, teenage skin, dark brown eyes',
        hairStyle: 'Long wavy',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Deep olive',
        fullDescription: 'Mariana is a 17-year-old Hispanic girl with a full-figured developing build. Her fuller round youthful face has soft features with teenage skin and dark brown eyes. She has long wavy black hair and a full build at 162cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'HSP_TN_F_XXXL_001',
        name: 'Lucia',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Hispanic',
        size: 'XXXL',
        height: '160cm (5\'3")',
        weight: '96kg (212lbs)',
        build: 'Very full-figured developing build',
        facialFeatures: 'Very full round youthful face, fuller features, teenage skin, brown eyes',
        hairStyle: 'Medium curly',
        hairColor: 'Dark brown',
        eyeColor: 'Brown',
        skinTone: 'Warm tan',
        fullDescription: 'Lucia is a 16-year-old Hispanic girl with a very full-figured developing build. Her very full round youthful face has fuller features with teenage skin and brown eyes. She has medium curly dark brown hair and a very full build at 160cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Asian': {
      'XS': [{
        id: 'ASN_TN_F_XS_001',
        name: 'Mei',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Asian',
        size: 'XS',
        height: '150cm (4\'11")',
        weight: '40kg (88lbs)',
        build: 'Very petite delicate developing frame',
        facialFeatures: 'Youthful oval face, smooth fair skin, almond eyes, teenage freshness',
        hairStyle: 'Long straight',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Light golden',
        fullDescription: 'Mei is a very petite 15-year-old Asian girl with a delicate developing frame. Her youthful oval face has smooth fair skin with almond-shaped eyes. She has long straight black hair and maintains a petite build at 150cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'ASN_TN_F_S_001',
        name: 'Yuki',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Asian',
        size: 'S',
        height: '155cm (5\'1")',
        weight: '45kg (99lbs)',
        build: 'Slim petite developing build',
        facialFeatures: 'Heart-shaped youthful face, clear smooth complexion, bright eyes, teenage energy',
        hairStyle: 'Medium straight bob',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Fair',
        fullDescription: 'Yuki is a 16-year-old Asian girl with a slim petite developing build. Her heart-shaped youthful face has a clear smooth complexion with bright eyes. She has a medium straight black bob and maintains a slim build at 155cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'ASN_TN_F_M_001',
        name: 'Lin',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Asian',
        size: 'M',
        height: '157cm (5\'2")',
        weight: '50kg (110lbs)',
        build: 'Average developing build with natural proportions',
        facialFeatures: 'Oval youthful face, smooth skin, delicate features, teenage look',
        hairStyle: 'Long straight',
        hairColor: 'Dark brown',
        eyeColor: 'Brown',
        skinTone: 'Medium golden',
        fullDescription: 'Lin is a 16-year-old Asian girl with an average developing build. Her oval youthful face has smooth skin with delicate features. She has long straight dark brown hair and a balanced build at 157cm with natural proportions.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'ASN_TN_F_L_001',
        name: 'Hana',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Asian',
        size: 'L',
        height: '160cm (5\'3")',
        weight: '58kg (128lbs)',
        build: 'Fuller developing build with curves',
        facialFeatures: 'Round youthful face, fuller cheeks, smooth skin, dark eyes, teenage softness',
        hairStyle: 'Medium layered',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Warm beige',
        fullDescription: 'Hana is a 17-year-old Asian girl with a fuller developing build. Her round youthful face has fuller cheeks with smooth skin and dark eyes. She has medium layered black hair and maintains a fuller figure at 160cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'ASN_TN_F_XL_001',
        name: 'Suki',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Asian',
        size: 'XL',
        height: '157cm (5\'2")',
        weight: '68kg (150lbs)',
        build: 'Plus-size developing build with full curves',
        facialFeatures: 'Full round youthful face, fuller features, clear skin, dark eyes, teenage features',
        hairStyle: 'Short straight',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Fair',
        fullDescription: 'Suki is a 16-year-old Asian girl with a plus-size developing build. Her full round youthful face has fuller features with clear skin and dark eyes. She has short straight black hair and a fuller build at 157cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'ASN_TN_F_XXL_001',
        name: 'Jing',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Asian',
        size: 'XXL',
        height: '160cm (5\'3")',
        weight: '80kg (176lbs)',
        build: 'Full-figured developing build',
        facialFeatures: 'Fuller round youthful face, soft features, smooth teenage skin, brown eyes',
        hairStyle: 'Medium bob',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Light',
        fullDescription: 'Jing is a 17-year-old Asian girl with a full-figured developing build. Her fuller round youthful face has soft features with smooth teenage skin and brown eyes. She has a medium black bob and a full build at 160cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'ASN_TN_F_XXXL_001',
        name: 'Ayumi',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Asian',
        size: 'XXXL',
        height: '158cm (5\'2")',
        weight: '92kg (203lbs)',
        build: 'Very full-figured developing build',
        facialFeatures: 'Very full round youthful face, fuller features, teenage skin, dark brown eyes',
        hairStyle: 'Short layered',
        hairColor: 'Dark brown',
        eyeColor: 'Dark brown',
        skinTone: 'Fair',
        fullDescription: 'Ayumi is a 16-year-old Asian girl with a very full-figured developing build. Her very full round youthful face has fuller features with teenage skin and dark brown eyes. She has short layered dark brown hair and a very full build at 158cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Indian': {
      'XS': [{
        id: 'IND_TN_F_XS_001',
        name: 'Priya',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indian',
        size: 'XS',
        height: '150cm (4\'11")',
        weight: '41kg (90lbs)',
        build: 'Petite delicate developing frame',
        facialFeatures: 'Youthful oval face, smooth brown skin, large expressive dark eyes, teenage freshness',
        hairStyle: 'Long straight',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Medium brown',
        fullDescription: 'Priya is a petite 15-year-old Indian girl with a delicate developing frame. Her youthful oval face has smooth brown skin with large expressive dark eyes. She has long straight black hair and maintains a petite build at 150cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'IND_TN_F_S_001',
        name: 'Anika',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indian',
        size: 'S',
        height: '155cm (5\'1")',
        weight: '46kg (101lbs)',
        build: 'Slim petite developing build',
        facialFeatures: 'Heart-shaped youthful face, clear complexion, bright dark eyes, teenage energy',
        hairStyle: 'Medium wavy',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Warm brown',
        fullDescription: 'Anika is a 16-year-old Indian girl with a slim petite developing build. Her heart-shaped youthful face has a clear complexion with bright dark eyes. She has medium wavy black hair and maintains a slim build at 155cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'IND_TN_F_M_001',
        name: 'Diya',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indian',
        size: 'M',
        height: '157cm (5\'2")',
        weight: '51kg (112lbs)',
        build: 'Average developing build with natural curves',
        facialFeatures: 'Oval youthful face, smooth tan skin, expressive eyes, teenage features',
        hairStyle: 'Long braided',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Golden brown',
        fullDescription: 'Diya is a 16-year-old Indian girl with an average developing build. Her oval youthful face has smooth tan skin with expressive eyes. She has long braided black hair and a balanced build at 157cm with natural developing curves.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'IND_TN_F_L_001',
        name: 'Shreya',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indian',
        size: 'L',
        height: '160cm (5\'3")',
        weight: '60kg (132lbs)',
        build: 'Curvy developing build with fuller figure',
        facialFeatures: 'Round youthful face, fuller cheeks, smooth skin, dark eyes, teenage softness',
        hairStyle: 'Long straight',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Deep brown',
        fullDescription: 'Shreya is a 17-year-old Indian girl with a curvy developing build. Her round youthful face has fuller cheeks with smooth skin and dark eyes. She has long straight black hair and maintains a fuller figure at 160cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'IND_TN_F_XL_001',
        name: 'Kavya',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indian',
        size: 'XL',
        height: '157cm (5\'2")',
        weight: '70kg (154lbs)',
        build: 'Plus-size developing build with full curves',
        facialFeatures: 'Full round youthful face, fuller features, clear skin, brown eyes, teenage features',
        hairStyle: 'Medium tied back',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Medium brown',
        fullDescription: 'Kavya is a 16-year-old Indian girl with a plus-size developing build. Her full round youthful face has fuller features with clear skin and brown eyes. She has medium black hair tied back and a fuller build at 157cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'IND_TN_F_XXL_001',
        name: 'Riya',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indian',
        size: 'XXL',
        height: '160cm (5\'3")',
        weight: '82kg (181lbs)',
        build: 'Full-figured developing build',
        facialFeatures: 'Fuller round youthful face, soft features, smooth teenage skin, dark brown eyes',
        hairStyle: 'Shoulder-length wavy',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Warm brown',
        fullDescription: 'Riya is a 17-year-old Indian girl with a full-figured developing build. Her fuller round youthful face has soft features with smooth teenage skin and dark brown eyes. She has shoulder-length wavy black hair and a full build at 160cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'IND_TN_F_XXXL_001',
        name: 'Pooja',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indian',
        size: 'XXXL',
        height: '158cm (5\'2")',
        weight: '94kg (207lbs)',
        build: 'Very full-figured developing build',
        facialFeatures: 'Very full round youthful face, fuller features, teenage skin, brown eyes',
        hairStyle: 'Long straight',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Deep brown',
        fullDescription: 'Pooja is a 16-year-old Indian girl with a very full-figured developing build. Her very full round youthful face has fuller features with teenage skin and brown eyes. She has long straight black hair and a very full build at 158cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Southeast Asian': {
      'XS': [{
        id: 'SEA_TN_F_XS_001',
        name: 'Mai',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Southeast Asian',
        size: 'XS',
        height: '148cm (4\'10")',
        weight: '39kg (86lbs)',
        build: 'Very petite delicate developing frame',
        facialFeatures: 'Youthful oval face, smooth tan skin, almond eyes, teenage freshness',
        hairStyle: 'Long straight',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Golden tan',
        fullDescription: 'Mai is a very petite 14-year-old Southeast Asian girl with a delicate developing frame. Her youthful oval face has smooth tan skin with almond-shaped eyes. She has long straight black hair and maintains a petite build at 148cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'SEA_TN_F_S_001',
        name: 'Linh',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Southeast Asian',
        size: 'S',
        height: '153cm (5\'0")',
        weight: '44kg (97lbs)',
        build: 'Slim petite developing build',
        facialFeatures: 'Heart-shaped youthful face, clear smooth complexion, bright eyes, teenage energy',
        hairStyle: 'Medium layered',
        hairColor: 'Dark brown',
        eyeColor: 'Brown',
        skinTone: 'Warm olive-tan',
        fullDescription: 'Linh is a 16-year-old Southeast Asian girl with a slim petite developing build. Her heart-shaped youthful face has a clear smooth complexion with bright eyes. She has medium layered dark brown hair and maintains a slim build at 153cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'SEA_TN_F_M_001',
        name: 'Siti',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Southeast Asian',
        size: 'M',
        height: '155cm (5\'1")',
        weight: '49kg (108lbs)',
        build: 'Average developing build with natural proportions',
        facialFeatures: 'Oval youthful face, smooth skin, delicate features, teenage look',
        hairStyle: 'Shoulder-length wavy',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Medium tan',
        fullDescription: 'Siti is a 16-year-old Southeast Asian girl with an average developing build. Her oval youthful face has smooth skin with delicate features. She has shoulder-length wavy black hair and a balanced build at 155cm with natural proportions.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'SEA_TN_F_L_001',
        name: 'Nong',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Southeast Asian',
        size: 'L',
        height: '157cm (5\'2")',
        weight: '57kg (126lbs)',
        build: 'Fuller developing build with curves',
        facialFeatures: 'Round youthful face, fuller cheeks, smooth skin, dark eyes, teenage softness',
        hairStyle: 'Medium straight',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Golden brown',
        fullDescription: 'Nong is a 17-year-old Southeast Asian girl with a fuller developing build. Her round youthful face has fuller cheeks with smooth skin and dark eyes. She has medium straight black hair and maintains a fuller figure at 157cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'SEA_TN_F_XL_001',
        name: 'Dewi',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Southeast Asian',
        size: 'XL',
        height: '155cm (5\'1")',
        weight: '67kg (148lbs)',
        build: 'Plus-size developing build with full curves',
        facialFeatures: 'Full round youthful face, fuller features, clear skin, brown eyes, teenage features',
        hairStyle: 'Short layered',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Deep tan',
        fullDescription: 'Dewi is a 16-year-old Southeast Asian girl with a plus-size developing build. Her full round youthful face has fuller features with clear skin and brown eyes. She has short layered black hair and a fuller build at 155cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'SEA_TN_F_XXL_001',
        name: 'Anh',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Southeast Asian',
        size: 'XXL',
        height: '158cm (5\'2")',
        weight: '79kg (174lbs)',
        build: 'Full-figured developing build',
        facialFeatures: 'Fuller round youthful face, soft features, smooth teenage skin, dark brown eyes',
        hairStyle: 'Medium tied back',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Medium tan',
        fullDescription: 'Anh is a 17-year-old Southeast Asian girl with a full-figured developing build. Her fuller round youthful face has soft features with smooth teenage skin and dark brown eyes. She has medium black hair tied back and a full build at 158cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'SEA_TN_F_XXXL_001',
        name: 'Pim',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Southeast Asian',
        size: 'XXXL',
        height: '157cm (5\'2")',
        weight: '91kg (201lbs)',
        build: 'Very full-figured developing build',
        facialFeatures: 'Very full round youthful face, fuller features, teenage skin, brown eyes',
        hairStyle: 'Short bob',
        hairColor: 'Dark brown',
        eyeColor: 'Brown',
        skinTone: 'Golden tan',
        fullDescription: 'Pim is a 16-year-old Southeast Asian girl with a very full-figured developing build. Her very full round youthful face has fuller features with teenage skin and brown eyes. She has a short dark brown bob and a very full build at 157cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Indigenous': {
      'XS': [{
        id: 'ING_TN_F_XS_001',
        name: 'Kaya',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indigenous',
        size: 'XS',
        height: '152cm (5\'0")',
        weight: '42kg (93lbs)',
        build: 'Petite compact developing frame',
        facialFeatures: 'Youthful oval face, smooth bronze skin, high cheekbones, strong features, teenage freshness',
        hairStyle: 'Long straight',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Medium bronze',
        fullDescription: 'Kaya is a petite 15-year-old Indigenous girl with a compact developing frame. Her youthful oval face has smooth bronze skin with high cheekbones and strong features. She has long straight black hair and maintains a petite build at 152cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'ING_TN_F_S_001',
        name: 'Aiyana',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indigenous',
        size: 'S',
        height: '157cm (5\'2")',
        weight: '47kg (104lbs)',
        build: 'Slim athletic developing build',
        facialFeatures: 'Heart-shaped youthful face, clear complexion, defined features, teenage energy',
        hairStyle: 'Medium braided',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Warm bronze',
        fullDescription: 'Aiyana is a 16-year-old Indigenous girl with a slim athletic developing build. Her heart-shaped youthful face has a clear complexion with defined features. She has medium braided black hair and maintains a slim build at 157cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'ING_TN_F_M_001',
        name: 'Winona',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indigenous',
        size: 'M',
        height: '160cm (5\'3")',
        weight: '53kg (117lbs)',
        build: 'Average developing build with natural curves',
        facialFeatures: 'Oval youthful face, smooth skin, strong bone structure, teenage features',
        hairStyle: 'Long loose',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Deep bronze',
        fullDescription: 'Winona is a 16-year-old Indigenous girl with an average developing build. Her oval youthful face has smooth skin with strong bone structure. She has long loose black hair and a balanced build at 160cm with natural developing curves.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'ING_TN_F_L_001',
        name: 'Nahla',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indigenous',
        size: 'L',
        height: '162cm (5\'4")',
        weight: '63kg (139lbs)',
        build: 'Curvy developing build with fuller figure',
        facialFeatures: 'Round youthful face, fuller cheeks, smooth skin, dark eyes, teenage softness',
        hairStyle: 'Long tied back',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Rich bronze',
        fullDescription: 'Nahla is a 17-year-old Indigenous girl with a curvy developing build. Her round youthful face has fuller cheeks with smooth skin and dark eyes. She has long black hair tied back and maintains a fuller figure at 162cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'ING_TN_F_XL_001',
        name: 'Tala',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indigenous',
        size: 'XL',
        height: '160cm (5\'3")',
        weight: '73kg (161lbs)',
        build: 'Plus-size developing build with full curves',
        facialFeatures: 'Full round youthful face, fuller features, clear skin, brown eyes, teenage features',
        hairStyle: 'Medium straight',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Medium bronze',
        fullDescription: 'Tala is a 16-year-old Indigenous girl with a plus-size developing build. Her full round youthful face has fuller features with clear skin and brown eyes. She has medium straight black hair and a fuller build at 160cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'ING_TN_F_XXL_001',
        name: 'Cholena',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indigenous',
        size: 'XXL',
        height: '163cm (5\'4")',
        weight: '85kg (187lbs)',
        build: 'Full-figured developing build',
        facialFeatures: 'Fuller round youthful face, soft features, smooth teenage skin, dark brown eyes',
        hairStyle: 'Shoulder-length wavy',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Deep bronze',
        fullDescription: 'Cholena is a 17-year-old Indigenous girl with a full-figured developing build. Her fuller round youthful face has soft features with smooth teenage skin and dark brown eyes. She has shoulder-length wavy black hair and a full build at 163cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'ING_TN_F_XXXL_001',
        name: 'Nita',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Indigenous',
        size: 'XXXL',
        height: '160cm (5\'3")',
        weight: '97kg (214lbs)',
        build: 'Very full-figured developing build',
        facialFeatures: 'Very full round youthful face, fuller features, teenage skin, brown eyes',
        hairStyle: 'Long braided',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Rich bronze',
        fullDescription: 'Nita is a 16-year-old Indigenous girl with a very full-figured developing build. Her very full round youthful face has fuller features with teenage skin and brown eyes. She has long braided black hair and a very full build at 160cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Diverse': {
      'XS': [{
        id: 'DIV_TN_F_XS_001',
        name: 'Maya',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Diverse',
        size: 'XS',
        height: '153cm (5\'0")',
        weight: '43kg (95lbs)',
        build: 'Petite slender developing frame',
        facialFeatures: 'Youthful oval face with blended features, olive-tan skin, unique mixed heritage look, teenage freshness',
        hairStyle: 'Medium curly',
        hairColor: 'Dark brown with hints of auburn',
        eyeColor: 'Light brown',
        skinTone: 'Warm olive-tan',
        fullDescription: 'Maya is a petite 15-year-old girl of diverse heritage with a slender developing frame. Her youthful oval face has blended features from her mixed background with olive-tan skin. She has medium curly dark brown hair with hints of auburn, light brown eyes, and maintains a petite build at 153cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'DIV_TN_F_S_001',
        name: 'Layla',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Diverse',
        size: 'S',
        height: '157cm (5\'2")',
        weight: '48kg (106lbs)',
        build: 'Slim athletic developing build',
        facialFeatures: 'Heart-shaped youthful face with unique blended features, clear complexion, teenage energy',
        hairStyle: 'Long wavy',
        hairColor: 'Black with brown highlights',
        eyeColor: 'Hazel-green',
        skinTone: 'Medium golden-brown',
        fullDescription: 'Layla is a 16-year-old girl of diverse heritage with a slim athletic developing build. Her heart-shaped youthful face has unique blended features with a clear complexion. She has long wavy black hair with brown highlights, hazel-green eyes, and maintains a slim build at 157cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'DIV_TN_F_M_001',
        name: 'Zara',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Diverse',
        size: 'M',
        height: '160cm (5\'3")',
        weight: '54kg (119lbs)',
        build: 'Average developing build with natural curves',
        facialFeatures: 'Oval youthful face with soft blended features, smooth skin, teenage features',
        hairStyle: 'Shoulder-length straight',
        hairColor: 'Dark brown',
        eyeColor: 'Brown',
        skinTone: 'Warm tan',
        fullDescription: 'Zara is a 16-year-old girl of diverse heritage with an average developing build. Her oval youthful face has soft blended features with smooth skin. She has shoulder-length straight dark brown hair, brown eyes, and a balanced build at 160cm with natural developing curves.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'DIV_TN_F_L_001',
        name: 'Amara',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Diverse',
        size: 'L',
        height: '162cm (5\'4")',
        weight: '64kg (141lbs)',
        build: 'Curvy developing build with fuller figure',
        facialFeatures: 'Round youthful face with soft blended features, fuller cheeks, clear skin, teenage softness',
        hairStyle: 'Medium layered',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Deep golden-brown',
        fullDescription: 'Amara is a 17-year-old girl of diverse heritage with a curvy developing build. Her round youthful face has soft blended features with fuller cheeks and clear skin. She has medium layered black hair, dark brown eyes, and maintains a fuller figure at 162cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'DIV_TN_F_XL_001',
        name: 'Nadia',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Diverse',
        size: 'XL',
        height: '160cm (5\'3")',
        weight: '74kg (163lbs)',
        build: 'Plus-size developing build with full curves',
        facialFeatures: 'Full round youthful face with blended features, fuller features, clear skin, teenage features',
        hairStyle: 'Short natural curly',
        hairColor: 'Dark brown',
        eyeColor: 'Light brown',
        skinTone: 'Medium brown',
        fullDescription: 'Nadia is a 16-year-old girl of diverse heritage with a plus-size developing build. Her full round youthful face has blended features with fuller features and clear skin. She has short natural curly dark brown hair, light brown eyes, and a fuller build at 160cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'DIV_TN_F_XXL_001',
        name: 'Aaliyah',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Diverse',
        size: 'XXL',
        height: '163cm (5\'4")',
        weight: '86kg (190lbs)',
        build: 'Full-figured developing build',
        facialFeatures: 'Fuller round youthful face with blended features, soft features, smooth teenage skin',
        hairStyle: 'Medium wavy',
        hairColor: 'Dark brown',
        eyeColor: 'Hazel',
        skinTone: 'Warm olive-brown',
        fullDescription: 'Aaliyah is a 17-year-old girl of diverse heritage with a full-figured developing build. Her fuller round youthful face has blended features with soft features and smooth teenage skin. She has medium wavy dark brown hair, hazel eyes, and a full build at 163cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'DIV_TN_F_XXXL_001',
        name: 'Jasmine',
        age: 'Teen',
        sex: 'Female',
        ethnicity: 'Diverse',
        size: 'XXXL',
        height: '160cm (5\'3")',
        weight: '98kg (216lbs)',
        build: 'Very full-figured developing build',
        facialFeatures: 'Very full round youthful face with blended features, fuller features, teenage skin',
        hairStyle: 'Short layered',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Deep tan',
        fullDescription: 'Jasmine is a 16-year-old girl of diverse heritage with a very full-figured developing build. Her very full round youthful face has blended features with fuller features and teenage skin. She has short layered black hair, brown eyes, and a very full build at 160cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    }
  },
  'Male': {
    'White': {
      'XS': [{
        id: 'WHT_TN_M_XS_001',
        name: 'Ethan',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'White',
        size: 'XS',
        height: '160cm (5\'3")',
        weight: '51kg (112lbs)',
        build: 'Slim lanky developing frame with minimal muscle',
        facialFeatures: 'Youthful oval face with soft features, clear skin, bright blue eyes, teenage awkwardness',
        hairStyle: 'Medium messy',
        hairColor: 'Light brown',
        eyeColor: 'Blue',
        skinTone: 'Fair',
        fullDescription: 'Ethan is a 15-year-old White boy with a slim lanky developing frame. His youthful oval face has soft features with clear skin and bright blue eyes. He has medium messy light brown hair and maintains a slim build at 160cm with minimal muscle development.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'WHT_TN_M_S_001',
        name: 'Noah',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'White',
        size: 'S',
        height: '168cm (5\'6")',
        weight: '59kg (130lbs)',
        build: 'Lean athletic developing build',
        facialFeatures: 'Angular youthful face, emerging jawline, clear complexion, green eyes, teenage features',
        hairStyle: 'Short styled',
        hairColor: 'Blonde',
        eyeColor: 'Green',
        skinTone: 'Light',
        fullDescription: 'Noah is a 16-year-old White boy with a lean athletic developing build. His angular youthful face has an emerging jawline with clear complexion and green eyes. He has short styled blonde hair and maintains a lean build at 168cm with developing muscle.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'WHT_TN_M_M_001',
        name: 'Liam',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'White',
        size: 'M',
        height: '170cm (5\'7")',
        weight: '66kg (145lbs)',
        build: 'Average developing build with emerging muscle',
        facialFeatures: 'Square youthful face, developing features, light facial hair beginning, hazel eyes, teenage look',
        hairStyle: 'Short neat',
        hairColor: 'Dark blonde',
        eyeColor: 'Hazel',
        skinTone: 'Medium fair',
        fullDescription: 'Liam is a 17-year-old White boy with an average developing build. His square youthful face has developing features with light facial hair beginning to show and hazel eyes. He has short neat dark blonde hair and a balanced build at 170cm with emerging muscle definition.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'WHT_TN_M_L_001',
        name: 'Mason',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'White',
        size: 'L',
        height: '173cm (5\'8")',
        weight: '76kg (168lbs)',
        build: 'Solid developing build with some bulk',
        facialFeatures: 'Broad youthful face, fuller features, sparse facial hair, blue eyes, teenage heaviness',
        hairStyle: 'Short messy',
        hairColor: 'Brown',
        eyeColor: 'Blue',
        skinTone: 'Fair',
        fullDescription: 'Mason is a 17-year-old White boy with a solid developing build. His broad youthful face has fuller features with sparse facial hair and blue eyes. He has short messy brown hair and maintains a solid build at 173cm with some teenage bulk.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'WHT_TN_M_XL_001',
        name: 'Lucas',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'White',
        size: 'XL',
        height: '170cm (5\'7")',
        weight: '87kg (192lbs)',
        build: 'Heavy developing build with fuller frame',
        facialFeatures: 'Full round youthful face, softer features, light stubble starting, gray-blue eyes, teenage weight',
        hairStyle: 'Short styled',
        hairColor: 'Light brown',
        eyeColor: 'Gray-blue',
        skinTone: 'Fair',
        fullDescription: 'Lucas is a 16-year-old White boy with a heavy developing build. His full round youthful face has softer features with light stubble starting and gray-blue eyes. He has short styled light brown hair and maintains a fuller frame at 170cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'WHT_TN_M_XXL_001',
        name: 'Logan',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'White',
        size: 'XXL',
        height: '173cm (5\'8")',
        weight: '100kg (220lbs)',
        build: 'Very heavy developing build',
        facialFeatures: 'Fuller round youthful face, soft features, emerging facial hair, hazel eyes, teenage heaviness',
        hairStyle: 'Short messy',
        hairColor: 'Dark brown',
        eyeColor: 'Hazel',
        skinTone: 'Medium fair',
        fullDescription: 'Logan is a 17-year-old White boy with a very heavy developing build. His fuller round youthful face has soft features with emerging facial hair and hazel eyes. He has short messy dark brown hair and a very heavy frame at 173cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'WHT_TN_M_XXXL_001',
        name: 'Jackson',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'White',
        size: 'XXXL',
        height: '175cm (5\'9")',
        weight: '115kg (254lbs)',
        build: 'Extremely heavy developing build',
        facialFeatures: 'Very full round youthful face, fuller features, light facial hair, blue eyes, significant teenage weight',
        hairStyle: 'Short neat',
        hairColor: 'Blonde',
        eyeColor: 'Blue',
        skinTone: 'Light',
        fullDescription: 'Jackson is a 16-year-old White boy with an extremely heavy developing build. His very full round youthful face has fuller features with light facial hair and blue eyes. He has short neat blonde hair and an extremely heavy frame at 175cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Black': {
      'XS': [{
        id: 'BLK_TN_M_XS_001',
        name: 'Jordan',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Black',
        size: 'XS',
        height: '163cm (5\'4")',
        weight: '53kg (117lbs)',
        build: 'Slim lanky developing frame with minimal muscle',
        facialFeatures: 'Youthful oval face, smooth dark skin, expressive eyes, emerging features, teenage look',
        hairStyle: 'Short fade',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Deep brown',
        fullDescription: 'Jordan is a 15-year-old Black boy with a slim lanky developing frame. His youthful oval face has smooth dark skin with expressive eyes and emerging features. He has a short fade in black hair and maintains a slim build at 163cm with minimal muscle development.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'BLK_TN_M_S_001',
        name: 'Isaiah',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Black',
        size: 'S',
        height: '170cm (5\'7")',
        weight: '61kg (134lbs)',
        build: 'Lean athletic developing build',
        facialFeatures: 'Angular youthful face, strong emerging jawline, smooth complexion, dark eyes, teenage energy',
        hairStyle: 'Low fade',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Rich brown',
        fullDescription: 'Isaiah is a 16-year-old Black boy with a lean athletic developing build. His angular youthful face has a strong emerging jawline with smooth complexion and dark eyes. He has a low fade and maintains a lean build at 170cm with developing muscle.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'BLK_TN_M_M_001',
        name: 'Malik',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Black',
        size: 'M',
        height: '173cm (5\'8")',
        weight: '68kg (150lbs)',
        build: 'Average developing build with emerging muscle',
        facialFeatures: 'Square youthful face, developing features, light facial hair starting, brown eyes, teenage look',
        hairStyle: 'Short caesar',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Medium brown',
        fullDescription: 'Malik is a 17-year-old Black boy with an average developing build. His square youthful face has developing features with light facial hair starting to show and brown eyes. He has a short caesar cut and a balanced build at 173cm with emerging muscle definition.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'BLK_TN_M_L_001',
        name: 'Tyrell',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Black',
        size: 'L',
        height: '175cm (5\'9")',
        weight: '77kg (170lbs)',
        build: 'Solid developing build with some bulk',
        facialFeatures: 'Broad youthful face, fuller features, emerging beard, dark eyes, teenage heaviness',
        hairStyle: 'Short fade',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Dark brown',
        fullDescription: 'Tyrell is a 17-year-old Black boy with a solid developing build. His broad youthful face has fuller features with an emerging beard and dark eyes. He has a short fade and maintains a solid build at 175cm with some teenage bulk.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'BLK_TN_M_XL_001',
        name: 'DeShawn',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Black',
        size: 'XL',
        height: '173cm (5\'8")',
        weight: '89kg (196lbs)',
        build: 'Heavy developing build with fuller frame',
        facialFeatures: 'Full round youthful face, softer features, light facial hair, brown eyes, teenage weight',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Deep brown',
        fullDescription: 'DeShawn is a 16-year-old Black boy with a heavy developing build. His full round youthful face has softer features with light facial hair and brown eyes. He has short neat black hair and maintains a fuller frame at 173cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'BLK_TN_M_XXL_001',
        name: 'Jamar',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Black',
        size: 'XXL',
        height: '175cm (5\'9")',
        weight: '102kg (225lbs)',
        build: 'Very heavy developing build',
        facialFeatures: 'Fuller round youthful face, soft features, emerging facial hair, dark brown eyes, teenage heaviness',
        hairStyle: 'Short fade',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Rich dark brown',
        fullDescription: 'Jamar is a 17-year-old Black boy with a very heavy developing build. His fuller round youthful face has soft features with emerging facial hair and dark brown eyes. He has a short fade and a very heavy frame at 175cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'BLK_TN_M_XXXL_001',
        name: 'Rashad',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Black',
        size: 'XXXL',
        height: '178cm (5\'10")',
        weight: '117kg (258lbs)',
        build: 'Extremely heavy developing build',
        facialFeatures: 'Very full round youthful face, fuller features, light beard, brown eyes, significant teenage weight',
        hairStyle: 'Short caesar',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Deep brown',
        fullDescription: 'Rashad is a 16-year-old Black boy with an extremely heavy developing build. His very full round youthful face has fuller features with a light beard and brown eyes. He has a short caesar cut and an extremely heavy frame at 178cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Hispanic': {
      'XS': [{
        id: 'HSP_TN_M_XS_001',
        name: 'Diego',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Hispanic',
        size: 'XS',
        height: '160cm (5\'3")',
        weight: '50kg (110lbs)',
        build: 'Slim compact developing frame with minimal muscle',
        facialFeatures: 'Youthful oval face, smooth olive skin, warm brown eyes, emerging features, teenage look',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Warm olive',
        fullDescription: 'Diego is a 14-year-old Hispanic boy with a slim compact developing frame. His youthful oval face has smooth olive skin with warm brown eyes and emerging features. He has short neat black hair and maintains a slim build at 160cm with minimal muscle development.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'HSP_TN_M_S_001',
        name: 'Miguel',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Hispanic',
        size: 'S',
        height: '168cm (5\'6")',
        weight: '58kg (128lbs)',
        build: 'Lean athletic developing build',
        facialFeatures: 'Angular youthful face, emerging jawline, clear tan complexion, dark eyes, teenage energy',
        hairStyle: 'Short styled',
        hairColor: 'Dark brown',
        eyeColor: 'Dark brown',
        skinTone: 'Medium olive',
        fullDescription: 'Miguel is a 16-year-old Hispanic boy with a lean athletic developing build. His angular youthful face has an emerging jawline with clear tan complexion and dark eyes. He has short styled dark brown hair and maintains a lean build at 168cm with developing muscle.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'HSP_TN_M_M_001',
        name: 'Carlos',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Hispanic',
        size: 'M',
        height: '170cm (5\'7")',
        weight: '65kg (143lbs)',
        build: 'Average developing build with emerging muscle',
        facialFeatures: 'Square youthful face, developing features, sparse mustache, hazel-brown eyes, teenage look',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Hazel-brown',
        skinTone: 'Warm tan',
        fullDescription: 'Carlos is a 17-year-old Hispanic boy with an average developing build. His square youthful face has developing features with a sparse mustache starting and hazel-brown eyes. He has short neat black hair and a balanced build at 170cm with emerging muscle definition.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'HSP_TN_M_L_001',
        name: 'Jose',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Hispanic',
        size: 'L',
        height: '173cm (5\'8")',
        weight: '75kg (165lbs)',
        build: 'Solid developing build with some bulk',
        facialFeatures: 'Broad youthful face, fuller features, emerging facial hair, dark eyes, teenage heaviness',
        hairStyle: 'Short messy',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Golden olive',
        fullDescription: 'Jose is a 17-year-old Hispanic boy with a solid developing build. His broad youthful face has fuller features with emerging facial hair and dark eyes. He has short messy black hair and maintains a solid build at 173cm with some teenage bulk.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'HSP_TN_M_XL_001',
        name: 'Luis',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Hispanic',
        size: 'XL',
        height: '170cm (5\'7")',
        weight: '86kg (190lbs)',
        build: 'Heavy developing build with fuller frame',
        facialFeatures: 'Full round youthful face, softer features, light mustache, brown eyes, teenage weight',
        hairStyle: 'Short styled',
        hairColor: 'Dark brown',
        eyeColor: 'Brown',
        skinTone: 'Deep olive',
        fullDescription: 'Luis is a 16-year-old Hispanic boy with a heavy developing build. His full round youthful face has softer features with a light mustache and brown eyes. He has short styled dark brown hair and maintains a fuller frame at 170cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'HSP_TN_M_XXL_001',
        name: 'Antonio',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Hispanic',
        size: 'XXL',
        height: '173cm (5\'8")',
        weight: '99kg (218lbs)',
        build: 'Very heavy developing build',
        facialFeatures: 'Fuller round youthful face, soft features, emerging facial hair, dark brown eyes, teenage heaviness',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Warm olive',
        fullDescription: 'Antonio is a 17-year-old Hispanic boy with a very heavy developing build. His fuller round youthful face has soft features with emerging facial hair and dark brown eyes. He has short neat black hair and a very heavy frame at 173cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'HSP_TN_M_XXXL_001',
        name: 'Fernando',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Hispanic',
        size: 'XXXL',
        height: '175cm (5\'9")',
        weight: '114kg (251lbs)',
        build: 'Extremely heavy developing build',
        facialFeatures: 'Very full round youthful face, fuller features, light beard, brown eyes, significant teenage weight',
        hairStyle: 'Short messy',
        hairColor: 'Dark brown',
        eyeColor: 'Brown',
        skinTone: 'Deep tan',
        fullDescription: 'Fernando is a 16-year-old Hispanic boy with an extremely heavy developing build. His very full round youthful face has fuller features with a light beard and brown eyes. He has short messy dark brown hair and an extremely heavy frame at 175cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Asian': {
      'XS': [{
        id: 'ASN_TN_M_XS_001',
        name: 'Kai',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Asian',
        size: 'XS',
        height: '158cm (5\'2")',
        weight: '49kg (108lbs)',
        build: 'Slim petite developing frame with minimal muscle',
        facialFeatures: 'Youthful oval face, smooth fair skin, almond-shaped eyes, emerging features, teenage look',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Light golden',
        fullDescription: 'Kai is a 15-year-old Asian boy with a slim petite developing frame. His youthful oval face has smooth fair skin with almond-shaped eyes and emerging features. He has short neat black hair and maintains a slim build at 158cm with minimal muscle development.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'ASN_TN_M_S_001',
        name: 'Yuki',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Asian',
        size: 'S',
        height: '165cm (5\'5")',
        weight: '57kg (126lbs)',
        build: 'Lean slim developing build',
        facialFeatures: 'Angular youthful face, emerging jawline, clear complexion, dark eyes, teenage energy',
        hairStyle: 'Short styled',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Fair',
        fullDescription: 'Yuki is a 16-year-old Asian boy with a lean slim developing build. His angular youthful face has an emerging jawline with clear complexion and dark eyes. He has short styled black hair and maintains a lean build at 165cm with developing muscle.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'ASN_TN_M_M_001',
        name: 'Chen',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Asian',
        size: 'M',
        height: '168cm (5\'6")',
        weight: '63kg (139lbs)',
        build: 'Average developing build with emerging muscle',
        facialFeatures: 'Square youthful face, developing features, minimal facial hair, brown eyes, teenage look',
        hairStyle: 'Short neat',
        hairColor: 'Dark brown',
        eyeColor: 'Brown',
        skinTone: 'Medium golden',
        fullDescription: 'Chen is a 17-year-old Asian boy with an average developing build. His square youthful face has developing features with minimal facial hair and brown eyes. He has short neat dark brown hair and a balanced build at 168cm with emerging muscle definition.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'ASN_TN_M_L_001',
        name: 'Wei',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Asian',
        size: 'L',
        height: '170cm (5\'7")',
        weight: '72kg (159lbs)',
        build: 'Solid developing build with some bulk',
        facialFeatures: 'Broad youthful face, fuller features, sparse facial hair, dark eyes, teenage heaviness',
        hairStyle: 'Short messy',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Warm beige',
        fullDescription: 'Wei is a 17-year-old Asian boy with a solid developing build. His broad youthful face has fuller features with sparse facial hair and dark eyes. He has short messy black hair and maintains a solid build at 170cm with some teenage bulk.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'ASN_TN_M_XL_001',
        name: 'Takeshi',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Asian',
        size: 'XL',
        height: '168cm (5\'6")',
        weight: '83kg (183lbs)',
        build: 'Heavy developing build with fuller frame',
        facialFeatures: 'Full round youthful face, softer features, minimal facial hair, dark eyes, teenage weight',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Fair',
        fullDescription: 'Takeshi is a 16-year-old Asian boy with a heavy developing build. His full round youthful face has softer features with minimal facial hair and dark eyes. He has short neat black hair and maintains a fuller frame at 168cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'ASN_TN_M_XXL_001',
        name: 'Akira',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Asian',
        size: 'XXL',
        height: '170cm (5\'7")',
        weight: '96kg (212lbs)',
        build: 'Very heavy developing build',
        facialFeatures: 'Fuller round youthful face, soft features, light facial hair, brown eyes, teenage heaviness',
        hairStyle: 'Short styled',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Light',
        fullDescription: 'Akira is a 17-year-old Asian boy with a very heavy developing build. His fuller round youthful face has soft features with light facial hair and brown eyes. He has short styled black hair and a very heavy frame at 170cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'ASN_TN_M_XXXL_001',
        name: 'Hiroshi',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Asian',
        size: 'XXXL',
        height: '173cm (5\'8")',
        weight: '110kg (243lbs)',
        build: 'Extremely heavy developing build',
        facialFeatures: 'Very full round youthful face, fuller features, minimal facial hair, dark brown eyes, significant teenage weight',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Fair',
        fullDescription: 'Hiroshi is a 16-year-old Asian boy with an extremely heavy developing build. His very full round youthful face has fuller features with minimal facial hair and dark brown eyes. He has short neat black hair and an extremely heavy frame at 173cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Indian': {
      'XS': [{
        id: 'IND_TN_M_XS_001',
        name: 'Arjun',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indian',
        size: 'XS',
        height: '158cm (5\'2")',
        weight: '50kg (110lbs)',
        build: 'Slim lean developing frame with minimal muscle',
        facialFeatures: 'Youthful oval face, smooth brown skin, large expressive eyes, emerging features, teenage look',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Medium brown',
        fullDescription: 'Arjun is a 15-year-old Indian boy with a slim lean developing frame. His youthful oval face has smooth brown skin with large expressive eyes and emerging features. He has short neat black hair and maintains a slim build at 158cm with minimal muscle development.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'IND_TN_M_S_001',
        name: 'Rohan',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indian',
        size: 'S',
        height: '165cm (5\'5")',
        weight: '58kg (128lbs)',
        build: 'Lean slim developing build',
        facialFeatures: 'Angular youthful face, emerging jawline, clear tan complexion, dark eyes, teenage energy',
        hairStyle: 'Short styled',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Warm brown',
        fullDescription: 'Rohan is a 16-year-old Indian boy with a lean slim developing build. His angular youthful face has an emerging jawline with clear tan complexion and dark eyes. He has short styled black hair and maintains a lean build at 165cm with developing muscle.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'IND_TN_M_M_001',
        name: 'Raj',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indian',
        size: 'M',
        height: '168cm (5\'6")',
        weight: '64kg (141lbs)',
        build: 'Average developing build with emerging muscle',
        facialFeatures: 'Square youthful face, developing features, light mustache starting, brown eyes, teenage look',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Golden brown',
        fullDescription: 'Raj is a 17-year-old Indian boy with an average developing build. His square youthful face has developing features with a light mustache starting and brown eyes. He has short neat black hair and a balanced build at 168cm with emerging muscle definition.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'IND_TN_M_L_001',
        name: 'Vikram',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indian',
        size: 'L',
        height: '170cm (5\'7")',
        weight: '73kg (161lbs)',
        build: 'Solid developing build with some bulk',
        facialFeatures: 'Broad youthful face, fuller features, emerging facial hair, dark eyes, teenage heaviness',
        hairStyle: 'Short messy',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Deep brown',
        fullDescription: 'Vikram is a 17-year-old Indian boy with a solid developing build. His broad youthful face has fuller features with emerging facial hair and dark eyes. He has short messy black hair and maintains a solid build at 170cm with some teenage bulk.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'IND_TN_M_XL_001',
        name: 'Dev',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indian',
        size: 'XL',
        height: '168cm (5\'6")',
        weight: '84kg (185lbs)',
        build: 'Heavy developing build with fuller frame',
        facialFeatures: 'Full round youthful face, softer features, light facial hair, brown eyes, teenage weight',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Medium brown',
        fullDescription: 'Dev is a 16-year-old Indian boy with a heavy developing build. His full round youthful face has softer features with light facial hair and brown eyes. He has short neat black hair and maintains a fuller frame at 168cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'IND_TN_M_XXL_001',
        name: 'Amit',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indian',
        size: 'XXL',
        height: '170cm (5\'7")',
        weight: '97kg (214lbs)',
        build: 'Very heavy developing build',
        facialFeatures: 'Fuller round youthful face, soft features, emerging facial hair, dark brown eyes, teenage heaviness',
        hairStyle: 'Short styled',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Warm brown',
        fullDescription: 'Amit is a 17-year-old Indian boy with a very heavy developing build. His fuller round youthful face has soft features with emerging facial hair and dark brown eyes. He has short styled black hair and a very heavy frame at 170cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'IND_TN_M_XXXL_001',
        name: 'Aditya',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indian',
        size: 'XXXL',
        height: '173cm (5\'8")',
        weight: '111kg (245lbs)',
        build: 'Extremely heavy developing build',
        facialFeatures: 'Very full round youthful face, fuller features, light mustache, brown eyes, significant teenage weight',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Deep brown',
        fullDescription: 'Aditya is a 16-year-old Indian boy with an extremely heavy developing build. His very full round youthful face has fuller features with a light mustache and brown eyes. He has short neat black hair and an extremely heavy frame at 173cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Southeast Asian': {
      'XS': [{
        id: 'SEA_TN_M_XS_001',
        name: 'Lian',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Southeast Asian',
        size: 'XS',
        height: '155cm (5\'1")',
        weight: '48kg (106lbs)',
        build: 'Slim petite developing frame with minimal muscle',
        facialFeatures: 'Youthful oval face, smooth tan skin, warm brown eyes, emerging features, teenage look',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Golden tan',
        fullDescription: 'Lian is a 14-year-old Southeast Asian boy with a slim petite developing frame. His youthful oval face has smooth tan skin with warm brown eyes and emerging features. He has short neat black hair and maintains a slim build at 155cm with minimal muscle development.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'SEA_TN_M_S_001',
        name: 'Kiet',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Southeast Asian',
        size: 'S',
        height: '163cm (5\'4")',
        weight: '56kg (123lbs)',
        build: 'Lean slim developing build',
        facialFeatures: 'Angular youthful face, emerging jawline, clear complexion, dark eyes, teenage energy',
        hairStyle: 'Short styled',
        hairColor: 'Dark brown',
        eyeColor: 'Brown',
        skinTone: 'Warm olive-tan',
        fullDescription: 'Kiet is a 16-year-old Southeast Asian boy with a lean slim developing build. His angular youthful face has an emerging jawline with clear complexion and dark eyes. He has short styled dark brown hair and maintains a lean build at 163cm with developing muscle.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'SEA_TN_M_M_001',
        name: 'Boun',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Southeast Asian',
        size: 'M',
        height: '165cm (5\'5")',
        weight: '62kg (137lbs)',
        build: 'Average developing build with emerging muscle',
        facialFeatures: 'Square youthful face, developing features, minimal facial hair, dark brown eyes, teenage look',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Medium tan',
        fullDescription: 'Boun is a 17-year-old Southeast Asian boy with an average developing build. His square youthful face has developing features with minimal facial hair and dark brown eyes. He has short neat black hair and a balanced build at 165cm with emerging muscle definition.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'SEA_TN_M_L_001',
        name: 'Phong',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Southeast Asian',
        size: 'L',
        height: '168cm (5\'6")',
        weight: '71kg (156lbs)',
        build: 'Solid developing build with some bulk',
        facialFeatures: 'Broad youthful face, fuller features, sparse facial hair, dark eyes, teenage heaviness',
        hairStyle: 'Short messy',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Golden brown',
        fullDescription: 'Phong is a 17-year-old Southeast Asian boy with a solid developing build. His broad youthful face has fuller features with sparse facial hair and dark eyes. He has short messy black hair and maintains a solid build at 168cm with some teenage bulk.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'SEA_TN_M_XL_001',
        name: 'Tuan',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Southeast Asian',
        size: 'XL',
        height: '165cm (5\'5")',
        weight: '82kg (181lbs)',
        build: 'Heavy developing build with fuller frame',
        facialFeatures: 'Full round youthful face, softer features, minimal facial hair, brown eyes, teenage weight',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Deep tan',
        fullDescription: 'Tuan is a 16-year-old Southeast Asian boy with a heavy developing build. His full round youthful face has softer features with minimal facial hair and brown eyes. He has short neat black hair and maintains a fuller frame at 165cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'SEA_TN_M_XXL_001',
        name: 'Nguyen',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Southeast Asian',
        size: 'XXL',
        height: '168cm (5\'6")',
        weight: '95kg (209lbs)',
        build: 'Very heavy developing build',
        facialFeatures: 'Fuller round youthful face, soft features, light facial hair, dark brown eyes, teenage heaviness',
        hairStyle: 'Short styled',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Medium tan',
        fullDescription: 'Nguyen is a 17-year-old Southeast Asian boy with a very heavy developing build. His fuller round youthful face has soft features with light facial hair and dark brown eyes. He has short styled black hair and a very heavy frame at 168cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'SEA_TN_M_XXXL_001',
        name: 'Somchai',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Southeast Asian',
        size: 'XXXL',
        height: '170cm (5\'7")',
        weight: '109kg (240lbs)',
        build: 'Extremely heavy developing build',
        facialFeatures: 'Very full round youthful face, fuller features, minimal facial hair, brown eyes, significant teenage weight',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Golden tan',
        fullDescription: 'Somchai is a 16-year-old Southeast Asian boy with an extremely heavy developing build. His very full round youthful face has fuller features with minimal facial hair and brown eyes. He has short neat black hair and an extremely heavy frame at 170cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Indigenous': {
      'XS': [{
        id: 'ING_TN_M_XS_001',
        name: 'Takoda',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indigenous',
        size: 'XS',
        height: '160cm (5\'3")',
        weight: '51kg (112lbs)',
        build: 'Slim compact developing frame with minimal muscle',
        facialFeatures: 'Youthful oval face, smooth bronze skin, dark expressive eyes, strong emerging features, teenage look',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Medium bronze',
        fullDescription: 'Takoda is a 15-year-old Indigenous boy with a slim compact developing frame. His youthful oval face has smooth bronze skin with dark expressive eyes and strong emerging features. He has short neat black hair and maintains a slim build at 160cm with minimal muscle development.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'ING_TN_M_S_001',
        name: 'Ahanu',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indigenous',
        size: 'S',
        height: '168cm (5\'6")',
        weight: '59kg (130lbs)',
        build: 'Lean athletic developing build',
        facialFeatures: 'Angular youthful face, strong emerging jawline, clear complexion, dark eyes, teenage energy',
        hairStyle: 'Short styled',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Warm bronze',
        fullDescription: 'Ahanu is a 16-year-old Indigenous boy with a lean athletic developing build. His angular youthful face has a strong emerging jawline with clear complexion and dark eyes. He has short styled black hair and maintains a lean build at 168cm with developing muscle.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'ING_TN_M_M_001',
        name: 'Koda',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indigenous',
        size: 'M',
        height: '170cm (5\'7")',
        weight: '66kg (145lbs)',
        build: 'Average developing build with emerging muscle',
        facialFeatures: 'Square youthful face, developing strong features, minimal facial hair, dark brown eyes, teenage look',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Deep bronze',
        fullDescription: 'Koda is a 17-year-old Indigenous boy with an average developing build. His square youthful face has developing strong features with minimal facial hair and dark brown eyes. He has short neat black hair and a balanced build at 170cm with emerging muscle definition.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'ING_TN_M_L_001',
        name: 'Elan',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indigenous',
        size: 'L',
        height: '173cm (5\'8")',
        weight: '76kg (168lbs)',
        build: 'Solid developing build with some bulk',
        facialFeatures: 'Broad youthful face, fuller features, emerging facial hair, dark eyes, teenage heaviness',
        hairStyle: 'Short messy',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Rich bronze',
        fullDescription: 'Elan is a 17-year-old Indigenous boy with a solid developing build. His broad youthful face has fuller features with emerging facial hair and dark eyes. He has short messy black hair and maintains a solid build at 173cm with some teenage bulk.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'ING_TN_M_XL_001',
        name: 'Chayton',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indigenous',
        size: 'XL',
        height: '170cm (5\'7")',
        weight: '87kg (192lbs)',
        build: 'Heavy developing build with fuller frame',
        facialFeatures: 'Full round youthful face, softer features, light facial hair, brown eyes, teenage weight',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Medium bronze',
        fullDescription: 'Chayton is a 16-year-old Indigenous boy with a heavy developing build. His full round youthful face has softer features with light facial hair and brown eyes. He has short neat black hair and maintains a fuller frame at 170cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'ING_TN_M_XXL_001',
        name: 'Mato',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indigenous',
        size: 'XXL',
        height: '173cm (5\'8")',
        weight: '100kg (220lbs)',
        build: 'Very heavy developing build',
        facialFeatures: 'Fuller round youthful face, soft features, emerging facial hair, dark brown eyes, teenage heaviness',
        hairStyle: 'Short styled',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Deep bronze',
        fullDescription: 'Mato is a 17-year-old Indigenous boy with a very heavy developing build. His fuller round youthful face has soft features with emerging facial hair and dark brown eyes. He has short styled black hair and a very heavy frame at 173cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'ING_TN_M_XXXL_001',
        name: 'Nikan',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Indigenous',
        size: 'XXXL',
        height: '175cm (5\'9")',
        weight: '114kg (251lbs)',
        build: 'Extremely heavy developing build',
        facialFeatures: 'Very full round youthful face, fuller features, light facial hair, brown eyes, significant teenage weight',
        hairStyle: 'Short neat',
        hairColor: 'Black',
        eyeColor: 'Brown',
        skinTone: 'Rich bronze',
        fullDescription: 'Nikan is a 16-year-old Indigenous boy with an extremely heavy developing build. His very full round youthful face has fuller features with light facial hair and brown eyes. He has short neat black hair and an extremely heavy frame at 175cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    },
    'Diverse': {
      'XS': [{
        id: 'DIV_TN_M_XS_001',
        name: 'Kai',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Diverse',
        size: 'XS',
        height: '160cm (5\'3")',
        weight: '52kg (115lbs)',
        build: 'Slim compact developing frame with minimal muscle',
        facialFeatures: 'Youthful oval face with blended features, olive-tan skin, unique mixed heritage look, teenage appearance',
        hairStyle: 'Short curly',
        hairColor: 'Dark brown',
        eyeColor: 'Light brown',
        skinTone: 'Warm olive-tan',
        fullDescription: 'Kai is a 15-year-old boy of diverse heritage with a slim compact developing frame. His youthful oval face has blended features from his mixed background with olive-tan skin. He has short curly dark brown hair, light brown eyes, and maintains a slim build at 160cm with minimal muscle development.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'S': [{
        id: 'DIV_TN_M_S_001',
        name: 'Andre',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Diverse',
        size: 'S',
        height: '168cm (5\'6")',
        weight: '60kg (132lbs)',
        build: 'Lean athletic developing build',
        facialFeatures: 'Angular youthful face with unique blended features, emerging jawline, clear complexion, teenage energy',
        hairStyle: 'Short wavy',
        hairColor: 'Black',
        eyeColor: 'Hazel-green',
        skinTone: 'Medium golden-brown',
        fullDescription: 'Andre is a 16-year-old boy of diverse heritage with a lean athletic developing build. His angular youthful face has unique blended features with an emerging jawline and clear complexion. He has short wavy black hair, hazel-green eyes, and maintains a lean build at 168cm with developing muscle.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'M': [{
        id: 'DIV_TN_M_M_001',
        name: 'Marcus',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Diverse',
        size: 'M',
        height: '170cm (5\'7")',
        weight: '67kg (148lbs)',
        build: 'Average developing build with emerging muscle',
        facialFeatures: 'Square youthful face with soft blended features, developing features, light facial hair, teenage look',
        hairStyle: 'Short neat',
        hairColor: 'Dark brown',
        eyeColor: 'Brown',
        skinTone: 'Warm tan',
        fullDescription: 'Marcus is a 17-year-old boy of diverse heritage with an average developing build. His square youthful face has soft blended features with developing features and light facial hair beginning. He has short neat dark brown hair, brown eyes, and a balanced build at 170cm with emerging muscle definition.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'L': [{
        id: 'DIV_TN_M_L_001',
        name: 'Elias',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Diverse',
        size: 'L',
        height: '173cm (5\'8")',
        weight: '77kg (170lbs)',
        build: 'Solid developing build with some bulk',
        facialFeatures: 'Broad youthful face with blended features, fuller features, emerging facial hair, teenage heaviness',
        hairStyle: 'Short messy',
        hairColor: 'Black',
        eyeColor: 'Dark brown',
        skinTone: 'Deep golden-brown',
        fullDescription: 'Elias is a 17-year-old boy of diverse heritage with a solid developing build. His broad youthful face has blended features with fuller features and emerging facial hair. He has short messy black hair, dark brown eyes, and maintains a solid build at 173cm with some teenage bulk.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XL': [{
        id: 'DIV_TN_M_XL_001',
        name: 'Daniel',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Diverse',
        size: 'XL',
        height: '170cm (5\'7")',
        weight: '88kg (194lbs)',
        build: 'Heavy developing build with fuller frame',
        facialFeatures: 'Full round youthful face with blended features, softer features, light facial hair, teenage weight',
        hairStyle: 'Short natural curly',
        hairColor: 'Dark brown',
        eyeColor: 'Light brown',
        skinTone: 'Medium brown',
        fullDescription: 'Daniel is a 16-year-old boy of diverse heritage with a heavy developing build. His full round youthful face has blended features with softer features and light facial hair. He has short natural curly dark brown hair, light brown eyes, and maintains a fuller frame at 170cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXL': [{
        id: 'DIV_TN_M_XXL_001',
        name: 'Isaiah',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Diverse',
        size: 'XXL',
        height: '173cm (5\'8")',
        weight: '101kg (223lbs)',
        build: 'Very heavy developing build',
        facialFeatures: 'Fuller round youthful face with blended features, soft features, emerging facial hair, teenage heaviness',
        hairStyle: 'Short wavy',
        hairColor: 'Black',
        eyeColor: 'Hazel',
        skinTone: 'Warm olive-brown',
        fullDescription: 'Isaiah is a 17-year-old boy of diverse heritage with a very heavy developing build. His fuller round youthful face has blended features with soft features and emerging facial hair. He has short wavy black hair, hazel eyes, and a very heavy frame at 173cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }],
      'XXXL': [{
        id: 'DIV_TN_M_XXXL_001',
        name: 'Gabriel',
        age: 'Teen',
        sex: 'Male',
        ethnicity: 'Diverse',
        size: 'XXXL',
        height: '175cm (5\'9")',
        weight: '115kg (254lbs)',
        build: 'Extremely heavy developing build',
        facialFeatures: 'Very full round youthful face with blended features, fuller features, light beard, significant teenage weight',
        hairStyle: 'Short styled',
        hairColor: 'Dark brown',
        eyeColor: 'Brown',
        skinTone: 'Deep tan',
        fullDescription: 'Gabriel is a 16-year-old boy of diverse heritage with an extremely heavy developing build. His very full round youthful face has blended features with fuller features and a light beard. He has short styled dark brown hair, brown eyes, and an extremely heavy frame at 175cm.',
        version: '1.0',
        createdDate: '2024-12-04'
      }]
    }
  }
};